"use client";

import { format } from "date-fns";
import { es } from "date-fns/locale";
import { CheckCircle, Clock, RefreshCw, User, Calendar, FileText } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";
import { type SettlementListItem } from "@/server/actions/vacation-settlement";

interface SettlementDetailDialogProps {
  settlement: SettlementListItem;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const statusConfig = {
  PENDING: {
    label: "Pendiente",
    variant: "outline" as const,
    icon: Clock,
    color: "text-yellow-600 dark:text-yellow-400",
  },
  PAID: {
    label: "Pagada",
    variant: "default" as const,
    icon: CheckCircle,
    color: "text-green-600 dark:text-green-400",
  },
  COMPENSATED: {
    label: "Compensada",
    variant: "secondary" as const,
    icon: RefreshCw,
    color: "text-blue-600 dark:text-blue-400",
  },
};

export function SettlementDetailDialog({ settlement, open, onOpenChange }: SettlementDetailDialogProps) {
  const status = settlement.status as keyof typeof statusConfig;
  const statusInfo = statusConfig[status];
  const StatusIcon = statusInfo.icon;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>Detalle de liquidación</DialogTitle>
          <DialogDescription>Información completa de la liquidación de vacaciones</DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          {/* Información del empleado */}
          <div className="flex items-start gap-4">
            <div className="bg-primary/10 rounded-full p-3">
              <User className="text-primary h-6 w-6" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">{settlement.employeeName}</h3>
              {settlement.employeeNumber && (
                <p className="text-muted-foreground text-sm">{settlement.employeeNumber}</p>
              )}
            </div>
            <Badge variant={statusInfo.variant} className="gap-1">
              <StatusIcon className="h-3 w-3" />
              {statusInfo.label}
            </Badge>
          </div>

          <Separator />

          {/* Fecha y tipo */}
          <div className="grid grid-cols-2 gap-4">
            <div className="flex items-center gap-2">
              <Calendar className="text-muted-foreground h-4 w-4" />
              <div>
                <p className="text-muted-foreground text-sm">Fecha de liquidación</p>
                <p className="font-medium">{format(new Date(settlement.settlementDate), "PPP", { locale: es })}</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <FileText className="text-muted-foreground h-4 w-4" />
              <div>
                <p className="text-muted-foreground text-sm">Tipo</p>
                <p className="font-medium">{settlement.isAutoGenerated ? "Automática" : "Manual"}</p>
              </div>
            </div>
          </div>

          <Separator />

          {/* Desglose del cálculo */}
          <div className="space-y-3">
            <h4 className="font-medium">Desglose del cálculo</h4>

            <div className="bg-muted/30 space-y-2 rounded-lg border p-4">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Días devengados</span>
                <span className="font-mono">{settlement.accruedDays.toFixed(2)} días</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Días disfrutados</span>
                <span className="font-mono text-red-600 dark:text-red-400">-{settlement.usedDays.toFixed(2)} días</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Días pendientes de aprobación</span>
                <span className="font-mono text-yellow-600 dark:text-yellow-400">
                  -{settlement.pendingDays.toFixed(2)} días
                </span>
              </div>

              <Separator className="my-2" />

              <div className="flex items-center justify-between">
                <span className="font-medium">Saldo final</span>
                <span
                  className={cn(
                    "font-mono text-lg font-bold",
                    settlement.balanceDays >= 0
                      ? "text-green-600 dark:text-green-400"
                      : "text-red-600 dark:text-red-400",
                  )}
                >
                  {settlement.balanceDays >= 0 ? "+" : ""}
                  {settlement.balanceDays.toFixed(2)} días
                </span>
              </div>
            </div>

            {settlement.balanceDays > 0 && (
              <p className="text-muted-foreground text-sm">
                El empleado tiene <strong>{settlement.balanceDays.toFixed(2)} días</strong> a su favor que deben ser
                liquidados o compensados.
              </p>
            )}
            {settlement.balanceDays < 0 && (
              <p className="text-muted-foreground text-sm">
                El empleado ha disfrutado <strong>{Math.abs(settlement.balanceDays).toFixed(2)} días</strong> más de los
                devengados. Este importe puede ser descontado.
              </p>
            )}
            {settlement.balanceDays === 0 && (
              <p className="text-muted-foreground text-sm">
                El empleado ha disfrutado exactamente los días devengados. No hay saldo pendiente.
              </p>
            )}
          </div>

          {/* Notas */}
          {settlement.notes && (
            <>
              <Separator />
              <div>
                <h4 className="mb-2 font-medium">Notas</h4>
                <p className="text-muted-foreground text-sm whitespace-pre-wrap">{settlement.notes}</p>
              </div>
            </>
          )}

          {/* Metadatos */}
          <Separator />
          <div className="text-muted-foreground space-y-1 text-xs">
            <p>Creada por: {settlement.createdByName}</p>
            <p>Fecha de creación: {format(new Date(settlement.createdAt), "PPP 'a las' HH:mm", { locale: es })}</p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
