"use client";

import { format } from "date-fns";
import { es } from "date-fns/locale";
import { CheckCircle, Clock, RefreshCw, User, Calendar, FileText, Download, Calculator } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { generateSettlementPdf } from "@/lib/pdf/generate-settlement-pdf";
import { cn } from "@/lib/utils";
import { type SettlementListItem } from "@/server/actions/vacation-settlement";

interface SettlementDetailDialogProps {
  settlement: SettlementListItem;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const statusConfig = {
  PENDING: {
    label: "Pendiente",
    variant: "outline" as const,
    icon: Clock,
    className: "text-yellow-600 border-yellow-600/20 bg-yellow-50 dark:bg-yellow-900/20 dark:text-yellow-400",
  },
  PAID: {
    label: "Pagada",
    variant: "default" as const,
    icon: CheckCircle,
    className: "bg-green-600 hover:bg-green-700",
  },
  COMPENSATED: {
    label: "Compensada",
    variant: "secondary" as const,
    icon: RefreshCw,
    className: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
  },
};

export function SettlementDetailDialog({ settlement, open, onOpenChange }: SettlementDetailDialogProps) {
  const status = settlement.status as keyof typeof statusConfig;
  const statusInfo = statusConfig[status];
  const StatusIcon = statusInfo.icon;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Detalle de Liquidación
          </DialogTitle>
          <DialogDescription>Referencia: {settlement.id.slice(0, 8).toUpperCase()}</DialogDescription>
        </DialogHeader>

        <div className="grid gap-6">
          {/* Header Card */}
          <div className="flex items-start justify-between rounded-lg border p-4 shadow-sm">
            <div className="flex items-center gap-4">
              <div className="bg-primary/10 text-primary flex h-12 w-12 items-center justify-center rounded-full">
                <User className="h-6 w-6" />
              </div>
              <div>
                <h3 className="text-lg font-semibold">{settlement.employeeName}</h3>
                <p className="text-muted-foreground flex items-center gap-1 text-sm">
                  ID: {settlement.employeeNumber ?? "N/A"}
                </p>
              </div>
            </div>
            <Badge variant={statusInfo.variant} className={cn("px-3 py-1 text-sm", statusInfo.className)}>
              <StatusIcon className="mr-1.5 h-4 w-4" />
              {statusInfo.label}
            </Badge>
          </div>

          {/* Info Grid */}
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div className="space-y-1">
              <span className="text-muted-foreground text-xs tracking-wider uppercase">Fecha Liquidación</span>
              <div className="flex items-center gap-2 font-medium">
                <Calendar className="text-muted-foreground h-4 w-4" />
                {format(new Date(settlement.settlementDate), "PPP", { locale: es })}
              </div>
            </div>
            <div className="space-y-1">
              <span className="text-muted-foreground text-xs tracking-wider uppercase">Tipo Generación</span>
              <div className="flex items-center gap-2 font-medium">
                <Calculator className="text-muted-foreground h-4 w-4" />
                {settlement.isAutoGenerated ? "Automática (Fin Contrato)" : "Manual"}
              </div>
            </div>
          </div>

          {/* Calculation Breakdown */}
          <div className="bg-card text-card-foreground overflow-hidden rounded-lg border shadow-sm">
            <div className="bg-muted/50 border-b px-4 py-3">
              <h4 className="flex items-center gap-2 text-sm font-medium">
                <Calculator className="h-4 w-4" />
                Desglose del Cálculo
              </h4>
            </div>
            <div className="space-y-3 p-4 text-sm">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Días devengados</span>
                <span className="font-mono">{settlement.accruedDays.toFixed(2)}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Días disfrutados</span>
                <span className="font-mono text-red-600 dark:text-red-400">-{settlement.usedDays.toFixed(2)}</span>
              </div>
              {settlement.pendingDays > 0 && (
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Días pendientes aprobación</span>
                  <span className="font-mono text-yellow-600 dark:text-yellow-400">
                    -{settlement.pendingDays.toFixed(2)}
                  </span>
                </div>
              )}

              <Separator />

              <div className="flex items-center justify-between pt-1">
                <span className="text-base font-semibold">Saldo Final</span>
                <span
                  className={cn(
                    "font-mono text-xl font-bold",
                    settlement.balanceDays >= 0
                      ? "text-green-600 dark:text-green-400"
                      : "text-red-600 dark:text-red-400",
                  )}
                >
                  {settlement.balanceDays >= 0 ? "+" : ""}
                  {settlement.balanceDays.toFixed(2)} días
                </span>
              </div>
              <p className="text-muted-foreground mt-2 text-xs">
                {settlement.balanceDays > 0
                  ? "Saldo a favor del empleado (a pagar)."
                  : settlement.balanceDays < 0
                    ? "Saldo a favor de la empresa (a descontar)."
                    : "Sin saldo pendiente."}
              </p>
            </div>
          </div>

          {/* Notes */}
          {settlement.notes && (
            <div className="space-y-2">
              <span className="text-muted-foreground text-xs tracking-wider uppercase">Notas / Observaciones</span>
              <div className="bg-muted/30 text-muted-foreground rounded-md p-3 text-sm italic">
                &quot;{settlement.notes}&quot;
              </div>
            </div>
          )}

          {/* Metadata Footer */}
          <div className="text-muted-foreground flex items-center justify-between border-t pt-4 text-xs">
            <span>Creado por: {settlement.createdByName}</span>
            <span>{format(new Date(settlement.createdAt), "dd/MM/yyyy HH:mm")}</span>
          </div>
        </div>

        <div className="flex justify-end gap-2 pt-2">
          <Button variant="outline" className="gap-2" onClick={() => generateSettlementPdf(settlement)}>
            <Download className="h-4 w-4" />
            Descargar PDF
          </Button>
          <Button onClick={() => onOpenChange(false)}>Cerrar</Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
