import { format } from "date-fns";
import { es } from "date-fns/locale";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import { type SettlementListItem } from "@/server/actions/vacation-settlement";

// Extender el tipo jsPDF para incluir autoTable
interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable: {
    finalY: number;
  };
}

const loadImage = (url: string): Promise<HTMLImageElement> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.src = url;
    img.crossOrigin = "Anonymous"; // Importante para evitar problemas de CORS
    img.onload = () => resolve(img);
    img.onerror = (err) => reject(err);
  });
};

export const generateSettlementPdf = async (settlement: SettlementListItem) => {
  const doc = new jsPDF() as jsPDFWithAutoTable;

  // Configuración de colores y fuentes
  const primaryColor = [41, 128, 185] as [number, number, number]; // Un azul profesional
  const secondaryColor = [127, 140, 141] as [number, number, number]; // Gris

  // --- Logo ---
  try {
    const logoImg = await loadImage("/logo/cutnobacklight.png");
    // Ajustar tamaño y posición del logo
    const logoWidth = 40;
    const logoHeight = (logoImg.height * logoWidth) / logoImg.width;
    doc.addImage(logoImg, "PNG", 150, 10, logoWidth, logoHeight);
  } catch (error) {
    console.error("Error cargando el logo:", error);
    // Continuar sin logo si falla
  }

  // --- Encabezado ---
  doc.setFontSize(22);
  doc.setTextColor(...primaryColor);
  doc.text("Liquidación de Vacaciones", 14, 22);

  doc.setFontSize(10);
  doc.setTextColor(...secondaryColor);
  doc.text(`Referencia: ${settlement.id.slice(0, 8).toUpperCase()}`, 14, 28);
  doc.text(`Fecha de emisión: ${format(new Date(), "PPP", { locale: es })}`, 14, 33);

  // Línea divisoria
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(14, 38, 196, 38);

  // --- Información del Empleado ---
  let currentY = 50;

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text("Datos del Empleado", 14, currentY);

  doc.setFontSize(10);
  doc.setTextColor(...secondaryColor);

  // Usamos autoTable para alinear datos del empleado limpiamente (sin bordes)
  autoTable(doc, {
    startY: currentY + 2,
    body: [
      ["Nombre:", settlement.employeeName],
      ["ID Empleado:", settlement.employeeNumber ?? "N/A"],
      ["Fecha de Liquidación:", format(new Date(settlement.settlementDate), "PPP", { locale: es })],
      ["Tipo:", settlement.isAutoGenerated ? "Automática (Fin Contrato)" : "Manual"],
    ],
    theme: "plain",
    styles: { cellPadding: 1, fontSize: 10 },
    columnStyles: {
      0: { fontStyle: "bold", width: 40 },
    },
  });

  currentY = doc.lastAutoTable.finalY + 10;

  // --- Detalles del Cálculo ---
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text("Desglose del Cálculo", 14, currentY);

  autoTable(doc, {
    startY: currentY + 3,
    head: [["Concepto", "Días"]],
    body: [
      ["Días Devengados (Generados)", settlement.accruedDays.toFixed(2)],
      ["Días Disfrutados", `-${settlement.usedDays.toFixed(2)}`],
      ["Pendientes de Aprobación", `-${settlement.pendingDays.toFixed(2)}`],
    ],
    theme: "striped",
    headStyles: { fillColor: primaryColor },
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: {
      1: { halign: "right", fontStyle: "bold" },
    },
  });

  currentY = doc.lastAutoTable.finalY + 5;

  // --- Saldo Final ---
  // Dibujar un cuadro para el total
  const balanceColor = settlement.balanceDays >= 0 ? [39, 174, 96] : [192, 57, 43]; // Verde o Rojo

  doc.setFillColor(245, 245, 245);
  doc.rect(14, currentY, 182, 20, "F");

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text("Saldo Final a Liquidar", 20, currentY + 13);

  doc.setFontSize(16);
  doc.setTextColor(balanceColor[0], balanceColor[1], balanceColor[2]); // Cast explícito para evitar error TS
  doc.setFont("helvetica", "bold");
  const balanceText = `${settlement.balanceDays >= 0 ? "+" : ""}${settlement.balanceDays.toFixed(2)} días`;
  const textWidth = doc.getTextWidth(balanceText);
  doc.text(balanceText, 190 - textWidth, currentY + 13);

  // Reset font
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);

  currentY += 30;

  // --- Notas ---
  if (settlement.notes) {
    doc.setFontSize(12);
    doc.text("Observaciones", 14, currentY);

    doc.setFontSize(10);
    doc.setTextColor(...secondaryColor);
    const splitNotes = doc.splitTextToSize(settlement.notes, 180);
    doc.text(splitNotes, 14, currentY + 7);

    currentY += 10 + splitNotes.length * 5;
  }

  // --- Firmas (Espacio reservado) ---
  currentY = Math.max(currentY, 220); // Asegurar que esté al final si hay espacio

  doc.setDrawColor(200, 200, 200);
  doc.line(14, currentY + 30, 80, currentY + 30);
  doc.line(110, currentY + 30, 176, currentY + 30);

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.text("Firma de la Empresa", 47, currentY + 35, { align: "center" });
  doc.text("Firma del Empleado", 143, currentY + 35, { align: "center" });

  // --- Pie de página ---
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Documento generado automáticamente por TimeNow ERP", 14, pageHeight - 10);

  // Descargar
  doc.save(
    `liquidacion_${settlement.employeeName.replace(/\s+/g, "_")}_${format(new Date(settlement.settlementDate), "yyyyMMdd")}.pdf`,
  );
};
